AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a list of ECR repositories

Parameters:
  TableSuffix:
    Type: String
    Description: Table suffix
  CreatedBy:
    Type: String
    Description: Created By
  ProjectName:
    Type: String
    Description: Name of the project

Resources:
  IndexingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-indexing-${TableSuffix}"
      EmptyOnDelete: true
  
  RetrieverRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-retriever-${TableSuffix}"
      EmptyOnDelete: true

  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-app-${TableSuffix}"
      EmptyOnDelete: true
  
  EvaluationRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-evaluation-${TableSuffix}"
      EmptyOnDelete: true
  
  RuntimeRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-runtime-${TableSuffix}"
      EmptyOnDelete: true

  CostComputeRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "flotorch-costcompute-${TableSuffix}"
      EmptyOnDelete: true

Outputs:
  AppRepositoryURI:
    Value: !GetAtt AppRepository.RepositoryUri
    Description: URI of the app repository

  EvaluationRepositoryURI:
    Value: !GetAtt EvaluationRepository.RepositoryUri
    Description: URI of the evaluation repository

  RetrieverRepositoryURI:
    Value: !GetAtt RetrieverRepository.RepositoryUri
    Description: URI of the retriever repository
  
  IndexingRepositoryURI:
    Value: !GetAtt IndexingRepository.RepositoryUri
    Description: URI of the indexing repository
  
  RuntimeRepositoryURI:
    Value: !GetAtt RuntimeRepository.RepositoryUri
    Description: URI of the runtime repository

  CostComputeRepositoryURI:
    Value: !GetAtt CostComputeRepository.RepositoryUri
    Description: URI of the AI repository
