CREATE TABLE "apikeys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "apikeys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"membershipId" integer,
	"createdBy" integer NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '',
	"key" text NOT NULL,
	"lastUsed" timestamp with time zone,
	"lastRefreshed" timestamp with time zone DEFAULT now(),
	"expiresAt" timestamp with time zone,
	"status" text DEFAULT 'Active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "apikeys_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"providerId" integer NOT NULL,
	"providerModelName" text NOT NULL,
	"providerModelParams" json DEFAULT '[]'::json NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"retryConfig" json,
	"costConfig" json,
	"status" text DEFAULT 'Active',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "configs_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
CREATE TABLE "gateways" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gateways_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"accessToken" text NOT NULL,
	"status" text DEFAULT 'Not Configured' NOT NULL,
	"lastSeen" timestamp with time zone DEFAULT now() NOT NULL,
	"url" text NOT NULL,
	"metadata" json,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "gateways_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "guardrails" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "guardrails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspace_id" integer,
	"name" text NOT NULL,
	"description" text,
	"config" json DEFAULT '{}'::json NOT NULL,
	"action" text NOT NULL,
	"severity" text NOT NULL,
	"type" text NOT NULL,
	"status" text DEFAULT 'Active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "guardrails_workspace_id_name_unique" UNIQUE NULLS NOT DISTINCT("workspace_id","name")
);
--> statement-breakpoint
CREATE TABLE "model_guardrails" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "model_guardrails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"hook" text NOT NULL,
	"modelId" integer NOT NULL,
	"modelVersionId" integer NOT NULL,
	"guardrailId" integer NOT NULL,
	"action" text,
	"severity" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"order" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "model_guardrails_hook_modelVersionId_guardrailId_unique" UNIQUE("hook","modelVersionId","guardrailId")
);
--> statement-breakpoint
CREATE TABLE "model_configs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_configs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"modelId" integer NOT NULL,
	"modelVersionId" integer NOT NULL,
	"configId" integer NOT NULL,
	"status" text DEFAULT 'Active' NOT NULL,
	"retryConfig" json,
	"costConfig" json,
	"weight" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "model_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "model_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"modelId" integer NOT NULL,
	"isPublished" boolean DEFAULT false NOT NULL,
	"publishedAt" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	"routingConfig" jsonb,
	"guardrails" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "model_versions_modelId_version_unique" UNIQUE("modelId","version")
);
--> statement-breakpoint
CREATE TABLE "models" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'Inactive' NOT NULL,
	"latestVersionId" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "models_name_unique" UNIQUE("name"),
	CONSTRAINT "models_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
CREATE TABLE "prompt_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prompt_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"promptId" integer NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"data" json NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "prompt_versions_promptId_version_unique" UNIQUE("promptId","version")
);
--> statement-breakpoint
CREATE TABLE "promptpartial_versions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promptpartial_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"promptpartialId" integer NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"isPublished" boolean DEFAULT false NOT NULL,
	"publishedAt" timestamp with time zone,
	"data" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promptpartial_versions_promptpartialId_version_unique" UNIQUE("promptpartialId","version")
);
--> statement-breakpoint
CREATE TABLE "promptpartials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "promptpartials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"latestVersionId" integer,
	"status" text DEFAULT 'Active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promptpartials_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
CREATE TABLE "prompts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prompts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"productionVersionId" integer,
	"status" text DEFAULT 'Active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "prompts_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
CREATE TABLE "providers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "providers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"sdk" text NOT NULL,
	"providerSlug" text NOT NULL,
	"configSchema" json DEFAULT '{}'::json NOT NULL,
	"config" text,
	"status" text DEFAULT 'Not Configured' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "providers_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"firstName" text NOT NULL,
	"lastName" text NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"isSuperAdmin" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "workspaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"slug" text NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspaces_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "workspace_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"workspaceId" integer NOT NULL,
	"userId" integer NOT NULL,
	"roleId" text DEFAULT 'WORKSPACE_MEMBER' NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workspace_users_workspaceId_userId_unique" UNIQUE("workspaceId","userId")
);
--> statement-breakpoint
ALTER TABLE "apikeys" ADD CONSTRAINT "apikeys_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "apikeys" ADD CONSTRAINT "apikeys_membershipId_workspace_users_id_fk" FOREIGN KEY ("membershipId") REFERENCES "public"."workspace_users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "apikeys" ADD CONSTRAINT "apikeys_createdBy_users_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "configs" ADD CONSTRAINT "configs_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "configs" ADD CONSTRAINT "configs_providerId_providers_id_fk" FOREIGN KEY ("providerId") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "guardrails" ADD CONSTRAINT "guardrails_workspace_id_workspaces_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_guardrails" ADD CONSTRAINT "model_guardrails_modelId_models_id_fk" FOREIGN KEY ("modelId") REFERENCES "public"."models"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_guardrails" ADD CONSTRAINT "model_guardrails_modelVersionId_model_versions_id_fk" FOREIGN KEY ("modelVersionId") REFERENCES "public"."model_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_guardrails" ADD CONSTRAINT "model_guardrails_guardrailId_guardrails_id_fk" FOREIGN KEY ("guardrailId") REFERENCES "public"."guardrails"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_configs" ADD CONSTRAINT "model_configs_modelId_models_id_fk" FOREIGN KEY ("modelId") REFERENCES "public"."models"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_configs" ADD CONSTRAINT "model_configs_modelVersionId_model_versions_id_fk" FOREIGN KEY ("modelVersionId") REFERENCES "public"."model_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_configs" ADD CONSTRAINT "model_configs_configId_configs_id_fk" FOREIGN KEY ("configId") REFERENCES "public"."configs"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "model_versions" ADD CONSTRAINT "model_versions_modelId_models_id_fk" FOREIGN KEY ("modelId") REFERENCES "public"."models"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "models" ADD CONSTRAINT "models_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "models" ADD CONSTRAINT "models_latestVersionId_model_versions_id_fk" FOREIGN KEY ("latestVersionId") REFERENCES "public"."model_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "prompt_versions" ADD CONSTRAINT "prompt_versions_promptId_prompts_id_fk" FOREIGN KEY ("promptId") REFERENCES "public"."prompts"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "promptpartial_versions" ADD CONSTRAINT "promptpartial_versions_promptpartialId_promptpartials_id_fk" FOREIGN KEY ("promptpartialId") REFERENCES "public"."promptpartials"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "promptpartials" ADD CONSTRAINT "promptpartials_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "promptpartials" ADD CONSTRAINT "promptpartials_latestVersionId_promptpartial_versions_id_fk" FOREIGN KEY ("latestVersionId") REFERENCES "public"."promptpartial_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "prompts" ADD CONSTRAINT "prompts_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "prompts" ADD CONSTRAINT "prompts_productionVersionId_prompt_versions_id_fk" FOREIGN KEY ("productionVersionId") REFERENCES "public"."prompt_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "providers" ADD CONSTRAINT "providers_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workspace_users" ADD CONSTRAINT "workspace_users_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "workspace_users" ADD CONSTRAINT "workspace_users_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "apikeys_workspaceId_index" ON "apikeys" USING btree ("workspaceId");--> statement-breakpoint
CREATE INDEX "apikeys_membershipId_index" ON "apikeys" USING btree ("membershipId");--> statement-breakpoint
CREATE INDEX "model_configs_modelId_index" ON "model_configs" USING btree ("modelId");--> statement-breakpoint
CREATE INDEX "model_configs_modelVersionId_index" ON "model_configs" USING btree ("modelVersionId");