CREATE TABLE "vectorstorage_guardrails" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vectorstorage_guardrails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"hook" text NOT NULL,
	"vectorStorageId" integer NOT NULL,
	"guardrailId" integer NOT NULL,
	"action" text,
	"severity" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"order" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vectorstorage_guardrails_vectorStorageId_guardrailId_unique" UNIQUE("vectorStorageId","guardrailId")
);
--> statement-breakpoint
CREATE TABLE "ragendpoints" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "ragendpoints_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" uuid DEFAULT gen_random_uuid() NOT NULL,
	"workspaceId" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"status" text DEFAULT 'Active' NOT NULL,
	"generatingModelId" integer NOT NULL,
	"generatingModelVersionId" integer,
	"vectorStorageId" integer NOT NULL,
	"config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ragendpoints_workspaceId_name_unique" UNIQUE("workspaceId","name")
);
--> statement-breakpoint
ALTER TABLE "vectorstorages" DROP CONSTRAINT "vectorstorages_retrievalModelVersionId_models_id_fk";
--> statement-breakpoint
ALTER TABLE "vectorstorages" DROP CONSTRAINT "vectorstorages_generatingModelVersionId_models_id_fk";
--> statement-breakpoint
ALTER TABLE "models" ALTER COLUMN "status" SET DEFAULT 'Active';--> statement-breakpoint
ALTER TABLE "vectorstorages" ALTER COLUMN "status" SET DEFAULT 'Active';--> statement-breakpoint
ALTER TABLE "vectorstorage_guardrails" ADD CONSTRAINT "vectorstorage_guardrails_vectorStorageId_vectorstorages_id_fk" FOREIGN KEY ("vectorStorageId") REFERENCES "public"."vectorstorages"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "vectorstorage_guardrails" ADD CONSTRAINT "vectorstorage_guardrails_guardrailId_guardrails_id_fk" FOREIGN KEY ("guardrailId") REFERENCES "public"."guardrails"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ragendpoints" ADD CONSTRAINT "ragendpoints_workspaceId_workspaces_id_fk" FOREIGN KEY ("workspaceId") REFERENCES "public"."workspaces"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ragendpoints" ADD CONSTRAINT "ragendpoints_generatingModelId_models_id_fk" FOREIGN KEY ("generatingModelId") REFERENCES "public"."models"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ragendpoints" ADD CONSTRAINT "ragendpoints_generatingModelVersionId_model_versions_id_fk" FOREIGN KEY ("generatingModelVersionId") REFERENCES "public"."model_versions"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ragendpoints" ADD CONSTRAINT "ragendpoints_vectorStorageId_vectorstorages_id_fk" FOREIGN KEY ("vectorStorageId") REFERENCES "public"."vectorstorages"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "vectorstorages" DROP COLUMN "retrievalModelVersionId";--> statement-breakpoint
ALTER TABLE "vectorstorages" DROP COLUMN "generatingModelVersionId";