apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-migrations
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  # SQL files will be populated here by the GitHub Action
  {{- range $path, $_ := .Files.Glob "sql/postgres/*.sql" }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
